#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyenchant
Version  : 2.0.0
Release  : 6
URL      : https://files.pythonhosted.org/packages/9e/54/04d88a59efa33fefb88133ceb638cdf754319030c28aadc5a379d82140ed/pyenchant-2.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/9e/54/04d88a59efa33fefb88133ceb638cdf754319030c28aadc5a379d82140ed/pyenchant-2.0.0.tar.gz
Summary  : Python bindings for the Enchant spellchecking system
Group    : Development/Tools
License  : LGPL-2.1
Requires: pyenchant-license = %{version}-%{release}
Requires: pyenchant-python = %{version}-%{release}
Requires: pyenchant-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : compat-enchant-soname1-dev
BuildRequires : enchant-dev
BuildRequires : glibc-locale

%description
pyenchant:  Python bindings for the Enchant spellchecker
========================================================

%package license
Summary: license components for the pyenchant package.
Group: Default

%description license
license components for the pyenchant package.


%package python
Summary: python components for the pyenchant package.
Group: Default
Requires: pyenchant-python3 = %{version}-%{release}

%description python
python components for the pyenchant package.


%package python3
Summary: python3 components for the pyenchant package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pyenchant package.


%prep
%setup -q -n pyenchant-2.0.0
cd %{_builddir}/pyenchant-2.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1576013317
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pyenchant
cp %{_builddir}/pyenchant-2.0.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/pyenchant/e60c2e780886f95df9c9ee36992b8edabec00bcc
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pyenchant/e60c2e780886f95df9c9ee36992b8edabec00bcc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
